package dif.clogic.other;

/**
 * Created with IntelliJ IDEA.
 * User: choeseung-il
 * Date: 13. 10. 29.
 * Time: 오후 11:10
 * To change this template use File | Settings | File Templates.
 */
public class Instruments {

    public static final String[] instruments = {
            "Acustic Grand",
            "Bright Acustic",
            "Electric Grand",
            "Honky-Tonk",
            "Electric Piano 1",
            "Electric Piano 2",
            "Herpsichord",
            "Clavinet",
            "Elesta",
            "Glockenspiel",
            "Music Box",
            "Vibraphone",
            "Marimba",
            "Xylophone",
            "Tubular Bells",
            "Dulcimer",
            "Drawbar Organ",
            "Percussive Organ",
            "Rock Organ",
            "Church Organ",
            "Reed Organ",
            "Accordion",
            "Harmonica",
            "Tango Accordian",
            "Acoustic Guitar (Nylon)",
            "Acoustic Guitar (Steel)",
            "Electric Guitar (Jazz)",
            "Electric Guitar (Clean)",
            "Electric Guitar (Muted)",
            "Overdriven Guitar",
            "Distortion Guitar",
            "Guitar Harmonics",
            "Acoustic Bass",
            "Electric Bass (Finger)",
            "Electric Bass (Pick)",
            "Fretless Bass",
            "Slap Bass 1",
            "Slap Bass 2",
            "Synth Bass 1",
            "Synth Bass 2",
            "Violin",
            "Viola",
            "Cello",
            "Contrabass",
            "Tremolo Strings",
            "Pizzicato Strings",
            "Orchestral Strings",
            "Timpani",
            "String Ensemble 1",
            "String Ensemble 2",
            "SynthStrings 1",
            "SynthStrings 2",
            "Choir Aahs",
            "Voice Oohs",
            "Synth Voice",
            "Orchestra Hit",
            "Trumpet",
            "Trombone",
            "Tuba",
            "Muted Trumpet",
            "French Horn",
            "Brass Section",
            "SynthBrass 1",
            "SynthBrass 2",
            "Soprano Sax",
            "Alto Sax",
            "Tenor Sax",
            "Baritone Sax",
            "Oboe",
            "English Horn",
            "Bassoon",
            "Clarinet",
            "Piccolo",
            "Flute",
            "Recorder",
            "Pan Flute",
            "Blown Bottle",
            "Skakuhachi",
            "Whistle",
            "Ocarina",
            "Lead 1 (Square)",
            "Lead 2 (Sawtooth)",
            "Lead 3 (Calliope)",
            "Lead 4 (Chiff)",
            "Lead 5 (Charang)",
            "Lead 6 (Voice)",
            "Lead 7 (Fifths)",
            "Lead 8 (Bass + Lead)",
            "Pad 1 (New age)",
            "Pad 2 (Warm)",
            "Pad 3 (Polysynth)",
            "Pad 4 (Choir)",
            "Pad 5 (Bowed)",
            "Pad 6 (Metallic)",
            "Pad 7 (Halo)",
            "Pad 8 (Sweep)",
            "FX 1 (Rain)",
            "FX 2 (Soundtrack)",
            "FX 3 (Crystal)",
            "FX 4 (Atmosphere)",
            "FX 5 (Brightness)",
            "FX 6 (Goblins)",
            "FX 7 (Echoes)",
            "FX 8 (Sci-fi)",
            "Sitar",
            "Banjo",
            "Shamisen",
            "Koto",
            "Kalimba",
            "Bagpipe",
            "Fiddle",
            "Shanai",
            "Tinkle Bell",
            "Agogo",
            "Steel Drums",
            "Woodblock",
            "Taiko Drum",
            "Melodic Tom",
            "Synth Drum",
            "Reverse Cymbal",
            "Guitar Fret Noise",
            "Breath Noise",
            "Seashore",
            "Bird Tweet",
            "Telephone Ring",
            "Helicopter",
            "Applause",
            "Gunshot"
    };
}
